## Reading malbourne housing price data

In [1]:
import zipfile
import os
from pathlib import Path
chwd = os.getcwd()

# unzipping the file

with zipfile.ZipFile(Path('data/melb_data.csv.zip'), 'r') as zip_file:
    zip_file.extractall('data/')

In [2]:
## checking the extracted files

for root, dir, files in os.walk(os.getcwd()):
    print(root, dir, files)

c:\Users\15887\Documents\Github\ml_learning\Kaggle ['data'] ['EDA.ipynb']
c:\Users\15887\Documents\Github\ml_learning\Kaggle\data [] ['melb_data.csv', 'melb_data.csv.zip']

In [7]:
## reading the dataset

import pandas as pd
pd.set_option('display.max_columns', None)
df = pd.read_csv('data/melb_data.csv')
print(df.shape)

(13580, 21)

In [8]:
## Checking data type of each columns
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB
None

### Notes on Specific Variables
Rooms: Number of rooms

Price: Price in dollars

Method: S - property sold; SP - property sold prior; PI - property passed in; PN - sold prior not disclosed; SN - sold not disclosed; NB - no bid; VB - vendor bid; W - withdrawn prior to auction; SA - sold after auction; SS - sold after auction price not disclosed. N/A - price or highest bid not available.

Type: br - bedroom(s); h - house,cottage,villa, semi,terrace; u - unit, duplex; t - townhouse; dev site - development site; o res - other residential.

SellerG: Real Estate Agent

Date: Date sold

Distance: Distance from CBD

Regionname: General Region (West, North West, North, North east …etc)

Propertycount: Number of properties that exist in the suburb.

Bedroom2 : Scraped # of Bedrooms (from different source)

Bathroom: Number of Bathrooms

Car: Number of carspots

Landsize: Land Size

BuildingArea: Building Size

CouncilArea: Governing council for the area

In [9]:
## Checking basic summary of the numeric columns

print(df.describe())

              Rooms         Price      Distance      Postcode      Bedroom2  \
count  13580.000000  1.358000e+04  13580.000000  13580.000000  13580.000000
mean       2.937997  1.075684e+06     10.137776   3105.301915      2.914728
std        0.955748  6.393107e+05      5.868725     90.676964      0.965921
min        1.000000  8.500000e+04      0.000000   3000.000000      0.000000
25%        2.000000  6.500000e+05      6.100000   3044.000000      2.000000
50%        3.000000  9.030000e+05      9.200000   3084.000000      3.000000
75%        3.000000  1.330000e+06     13.000000   3148.000000      3.000000
max       10.000000  9.000000e+06     48.100000   3977.000000     20.000000

           Bathroom           Car       Landsize  BuildingArea    YearBuilt  \
count  13580.000000  13518.000000   13580.000000   7130.000000  8205.000000
mean       1.534242      1.610075     558.416127    151.967650  1964.684217
std        0.691712      0.962634    3990.669241    541.014538    37.273762
min        0.000000      0.000000       0.000000      0.000000  1196.000000
25%        1.000000      1.000000     177.000000     93.000000  1940.000000
50%        1.000000      2.000000     440.000000    126.000000  1970.000000
75%        2.000000      2.000000     651.000000    174.000000  1999.000000
max        8.000000     10.000000  433014.000000  44515.000000  2018.000000

          Lattitude    Longtitude  Propertycount
count  13580.000000  13580.000000   13580.000000
mean     -37.809203    144.995216    7454.417378
std        0.079260      0.103916    4378.581772
min      -38.182550    144.431810     249.000000
25%      -37.856822    144.929600    4380.000000
50%      -37.802355    145.000100    6555.000000
75%      -37.756400    145.058305   10331.000000
max      -37.408530    145.526350   21650.000000

In [10]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [11]:
# Converting the categorical variables into numerical

from sklearn.preprocessing import LabelEncoder

lblEncoder = LabelEncoder()

In [15]:
for col in df.columns.to_list():
    if df[col].dtypes == 'object':
        print(col)
        df[f'{col}_num'] = lblEncoder.fit_transform(df[col])
        print(dict(zip(lblEncoder.classes_, lblEncoder.transform(lblEncoder.classes_))))

Suburb
{'Abbotsford': np.int64(0), 'Aberfeldie': np.int64(1), 'Airport West': np.int64(2), 'Albanvale': np.int64(3), 'Albert Park': np.int64(4), 'Albion': np.int64(5), 'Alphington': np.int64(6), 'Altona': np.int64(7), 'Altona Meadows': np.int64(8), 'Altona North': np.int64(9), 'Ardeer': np.int64(10), 'Armadale': np.int64(11), 'Ascot Vale': np.int64(12), 'Ashburton': np.int64(13), 'Ashwood': np.int64(14), 'Aspendale': np.int64(15), 'Aspendale Gardens': np.int64(16), 'Attwood': np.int64(17), 'Avondale Heights': np.int64(18), 'Bacchus Marsh': np.int64(19), 'Balaclava': np.int64(20), 'Balwyn': np.int64(21), 'Balwyn North': np.int64(22), 'Bayswater': np.int64(23), 'Bayswater North': np.int64(24), 'Beaconsfield': np.int64(25), 'Beaconsfield Upper': np.int64(26), 'Beaumaris': np.int64(27), 'Bellfield': np.int64(28), 'Bentleigh': np.int64(29), 'Bentleigh East': np.int64(30), 'Berwick': np.int64(31), 'Black Rock': np.int64(32), 'Blackburn': np.int64(33), 'Blackburn North': np.int64(34), 'Blackburn South': np.int64(35), 'Bonbeach': np.int64(36), 'Boronia': np.int64(37), 'Box Hill': np.int64(38), 'Braybrook': np.int64(39), 'Briar Hill': np.int64(40), 'Brighton': np.int64(41), 'Brighton East': np.int64(42), 'Broadmeadows': np.int64(43), 'Brookfield': np.int64(44), 'Brooklyn': np.int64(45), 'Brunswick': np.int64(46), 'Brunswick East': np.int64(47), 'Brunswick West': np.int64(48), 'Bulleen': np.int64(49), 'Bullengarook': np.int64(50), 'Bundoora': np.int64(51), 'Burnley': np.int64(52), 'Burnside': np.int64(53), 'Burnside Heights': np.int64(54), 'Burwood': np.int64(55), 'Burwood East': np.int64(56), 'Cairnlea': np.int64(57), 'Camberwell': np.int64(58), 'Campbellfield': np.int64(59), 'Canterbury': np.int64(60), 'Carlton': np.int64(61), 'Carlton North': np.int64(62), 'Carnegie': np.int64(63), 'Caroline Springs': np.int64(64), 'Carrum': np.int64(65), 'Carrum Downs': np.int64(66), 'Caulfield': np.int64(67), 'Caulfield East': np.int64(68), 'Caulfield North': np.int64(69), 'Caulfield South': np.int64(70), 'Chadstone': np.int64(71), 'Chelsea': np.int64(72), 'Chelsea Heights': np.int64(73), 'Cheltenham': np.int64(74), 'Chirnside Park': np.int64(75), 'Clarinda': np.int64(76), 'Clayton': np.int64(77), 'Clayton South': np.int64(78), 'Clifton Hill': np.int64(79), 'Coburg': np.int64(80), 'Coburg North': np.int64(81), 'Collingwood': np.int64(82), 'Coolaroo': np.int64(83), 'Craigieburn': np.int64(84), 'Cranbourne': np.int64(85), 'Cranbourne North': np.int64(86), 'Cremorne': np.int64(87), 'Croydon': np.int64(88), 'Croydon Hills': np.int64(89), 'Croydon North': np.int64(90), 'Croydon South': np.int64(91), 'Dallas': np.int64(92), 'Dandenong': np.int64(93), 'Dandenong North': np.int64(94), 'Deepdene': np.int64(95), 'Deer Park': np.int64(96), 'Delahey': np.int64(97), 'Derrimut': np.int64(98), 'Diamond Creek': np.int64(99), 'Diggers Rest': np.int64(100), 'Dingley Village': np.int64(101), 'Docklands': np.int64(102), 'Doncaster': np.int64(103), 'Doncaster East': np.int64(104), 'Donvale': np.int64(105), 'Doreen': np.int64(106), 'Doveton': np.int64(107), 'Eaglemont': np.int64(108), 'East Melbourne': np.int64(109), 'Edithvale': np.int64(110), 'Elsternwick': np.int64(111), 'Eltham': np.int64(112), 'Eltham North': np.int64(113), 'Elwood': np.int64(114), 'Emerald': np.int64(115), 'Endeavour Hills': np.int64(116), 'Epping': np.int64(117), 'Essendon': np.int64(118), 'Essendon North': np.int64(119), 'Essendon West': np.int64(120), 'Fairfield': np.int64(121), 'Fawkner': np.int64(122), 'Ferntree Gully': np.int64(123), 'Fitzroy': np.int64(124), 'Fitzroy North': np.int64(125), 'Flemington': np.int64(126), 'Footscray': np.int64(127), 'Forest Hill': np.int64(128), 'Frankston': np.int64(129), 'Frankston North': np.int64(130), 'Frankston South': np.int64(131), 'Gardenvale': np.int64(132), 'Gisborne': np.int64(133), 'Gladstone Park': np.int64(134), 'Glen Huntly': np.int64(135), 'Glen Iris': np.int64(136), 'Glen Waverley': np.int64(137), 'Glenroy': np.int64(138), 'Gowanbrae': np.int64(139), 'Greensborough': np.int64(140), 'Greenvale': np.int64(141), 'Hadfield': np.int64(142), 'Hallam': np.int64(143), 'Hampton': np.int64(144), 'Hampton East': np.int64(145), 'Hampton Park': np.int64(146), 'Hawthorn': np.int64(147), 'Hawthorn East': np.int64(148), 'Healesville': np.int64(149), 'Heathmont': np.int64(150), 'Heidelberg': np.int64(151), 'Heidelberg Heights': np.int64(152), 'Heidelberg West': np.int64(153), 'Highett': np.int64(154), 'Hillside': np.int64(155), 'Hoppers Crossing': np.int64(156), 'Hughesdale': np.int64(157), 'Huntingdale': np.int64(158), 'Hurstbridge': np.int64(159), 'Ivanhoe': np.int64(160), 'Ivanhoe East': np.int64(161), 'Jacana': np.int64(162), 'Kealba': np.int64(163), 'Keilor': np.int64(164), 'Keilor Downs': np.int64(165), 'Keilor East': np.int64(166), 'Keilor Lodge': np.int64(167), 'Keilor Park': np.int64(168), 'Kensington': np.int64(169), 'Kew': np.int64(170), 'Kew East': np.int64(171), 'Keysborough': np.int64(172), 'Kilsyth': np.int64(173), 'Kings Park': np.int64(174), 'Kingsbury': np.int64(175), 'Kingsville': np.int64(176), 'Knoxfield': np.int64(177), 'Kooyong': np.int64(178), 'Kurunjang': np.int64(179), 'Lalor': np.int64(180), 'Langwarrin': np.int64(181), 'Lower Plenty': np.int64(182), 'Maidstone': np.int64(183), 'Malvern': np.int64(184), 'Malvern East': np.int64(185), 'Maribyrnong': np.int64(186), 'McKinnon': np.int64(187), 'Meadow Heights': np.int64(188), 'Melbourne': np.int64(189), 'Melton': np.int64(190), 'Melton South': np.int64(191), 'Melton West': np.int64(192), 'Mentone': np.int64(193), 'Mernda': np.int64(194), 'Middle Park': np.int64(195), 'Mill Park': np.int64(196), 'Mitcham': np.int64(197), 'Monbulk': np.int64(198), 'Mont Albert': np.int64(199), 'Montmorency': np.int64(200), 'Montrose': np.int64(201), 'Moonee Ponds': np.int64(202), 'Moorabbin': np.int64(203), 'Mooroolbark': np.int64(204), 'Mordialloc': np.int64(205), 'Mount Evelyn': np.int64(206), 'Mount Waverley': np.int64(207), 'Mulgrave': np.int64(208), 'Murrumbeena': np.int64(209), 'Narre Warren': np.int64(210), 'New Gisborne': np.int64(211), 'Newport': np.int64(212), 'Niddrie': np.int64(213), 'Noble Park': np.int64(214), 'North Melbourne': np.int64(215), 'North Warrandyte': np.int64(216), 'Northcote': np.int64(217), 'Notting Hill': np.int64(218), 'Nunawading': np.int64(219), 'Oak Park': np.int64(220), 'Oakleigh': np.int64(221), 'Oakleigh East': np.int64(222), 'Oakleigh South': np.int64(223), 'Officer': np.int64(224), 'Ormond': np.int64(225), 'Pakenham': np.int64(226), 'Parkdale': np.int64(227), 'Parkville': np.int64(228), 'Pascoe Vale': np.int64(229), 'Plumpton': np.int64(230), 'Point Cook': np.int64(231), 'Port Melbourne': np.int64(232), 'Prahran': np.int64(233), 'Preston': np.int64(234), 'Princes Hill': np.int64(235), 'Reservoir': np.int64(236), 'Richmond': np.int64(237), 'Riddells Creek': np.int64(238), 'Ringwood': np.int64(239), 'Ringwood East': np.int64(240), 'Ringwood North': np.int64(241), 'Ripponlea': np.int64(242), 'Rockbank': np.int64(243), 'Rosanna': np.int64(244), 'Rowville': np.int64(245), 'Roxburgh Park': np.int64(246), 'Sandhurst': np.int64(247), 'Sandringham': np.int64(248), 'Scoresby': np.int64(249), 'Seabrook': np.int64(250), 'Seaford': np.int64(251), 'Seaholme': np.int64(252), 'Seddon': np.int64(253), 'Silvan': np.int64(254), 'Skye': np.int64(255), 'South Kingsville': np.int64(256), 'South Melbourne': np.int64(257), 'South Morang': np.int64(258), 'South Yarra': np.int64(259), 'Southbank': np.int64(260), 'Spotswood': np.int64(261), 'Springvale': np.int64(262), 'Springvale South': np.int64(263), 'St Albans': np.int64(264), 'St Helena': np.int64(265), 'St Kilda': np.int64(266), 'Strathmore': np.int64(267), 'Strathmore Heights': np.int64(268), 'Sunbury': np.int64(269), 'Sunshine': np.int64(270), 'Sunshine North': np.int64(271), 'Sunshine West': np.int64(272), 'Surrey Hills': np.int64(273), 'Sydenham': np.int64(274), 'Tarneit': np.int64(275), 'Taylors Hill': np.int64(276), 'Taylors Lakes': np.int64(277), 'Templestowe': np.int64(278), 'Templestowe Lower': np.int64(279), 'The Basin': np.int64(280), 'Thomastown': np.int64(281), 'Thornbury': np.int64(282), 'Toorak': np.int64(283), 'Travancore': np.int64(284), 'Truganina': np.int64(285), 'Tullamarine': np.int64(286), 'Upwey': np.int64(287), 'Vermont': np.int64(288), 'Vermont South': np.int64(289), 'Viewbank': np.int64(290), 'Wallan': np.int64(291), 'Wantirna': np.int64(292), 'Wantirna South': np.int64(293), 'Warrandyte': np.int64(294), 'Waterways': np.int64(295), 'Watsonia': np.int64(296), 'Watsonia North': np.int64(297), 'Werribee': np.int64(298), 'West Footscray': np.int64(299), 'West Melbourne': np.int64(300), 'Westmeadows': np.int64(301), 'Wheelers Hill': np.int64(302), 'Whittlesea': np.int64(303), 'Williams Landing': np.int64(304), 'Williamstown': np.int64(305), 'Williamstown North': np.int64(306), 'Windsor': np.int64(307), 'Wollert': np.int64(308), 'Wonga Park': np.int64(309), 'Wyndham Vale': np.int64(310), 'Yallambie': np.int64(311), 'Yarra Glen': np.int64(312), 'Yarraville': np.int64(313)}
Address

In [16]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Suburb_num,Address_num,Type_num,Method_num,SellerG_num,Date_num,CouncilArea_num,Regionname_num
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,0,12794,0,1,23,45,31,2
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,0,5943,0,1,23,47,31,2
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,0,9814,0,3,23,48,31,2
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0,0,9004,0,0,23,48,31,2
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0,0,10589,0,4,155,49,31,2

In [18]:
import datetime
df['PropAge'] = df['YearBuilt'] - datetime.datetime.today().year

In [ ]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount', 'Suburb_num',
       'Address_num', 'Type_num', 'Method_num', 'SellerG_num', 'Date_num',
       'CouncilArea_num', 'Regionname_num'],
      dtype='object')

In [20]:
features = [ 'Rooms', 'Type_num', 'Distance', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'PropAge', 'Propertycount','Suburb_num',
        'Method_num', 'Regionname_num' ]

df1 = df[features]
df1.head()

,Rooms,Type_num,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,PropAge,Propertycount,Suburb_num,Method_num,Regionname_num
0,2,0,2.5,2.0,1.0,1.0,202.0,NaN,NaN,4019.0,0,1,2
1,2,0,2.5,2.0,1.0,0.0,156.0,79.0,-125.0,4019.0,0,1,2
2,3,0,2.5,3.0,2.0,0.0,134.0,150.0,-125.0,4019.0,0,3,2
3,3,0,2.5,3.0,2.0,1.0,94.0,NaN,NaN,4019.0,0,0,2
4,4,0,2.5,3.0,1.0,2.0,120.0,142.0,-11.0,4019.0,0,4,2

In [26]:
df1['Car'].fillna(df1['Car'].mean(), inplace=True)
df1['BuildingArea'].fillna(df1['BuildingArea'].median(), inplace=True)
df1['PropAge'].fillna(df1['PropAge'].median(), inplace=True)
df1.isna().mean() * 100

C:\Users\15887\AppData\Local\Temp\ipykernel_7688\1355523480.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Car'].fillna(df1['Car'].mean(), inplace=True)
C:\Users\15887\AppData\Local\Temp\ipykernel_7688\1355523480.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Car'].fillna(df1['Car'].mean(), inplace=True)
C:\Users\15887\AppData\Local\Temp\ipykernel_7688\1355523480.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['BuildingArea'].fillna(df1['BuildingArea'].median(), inplace=True)
C:\Users\15887\AppData\Local\Temp\ipykernel_7688\1355523480.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['BuildingArea'].fillna(df1['BuildingArea'].median(), inplace=True)
C:\Users\15887\AppData\Local\Temp\ipykernel_7688\1355523480.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['PropAge'].fillna(df1['PropAge'].median(), inplace=True)
C:\Users\15887\AppData\Local\Temp\ipykernel_7688\1355523480.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['PropAge'].fillna(df1['PropAge'].median(), inplace=True)

Rooms             0.0
Type_num          0.0
Distance          0.0
Bedroom2          0.0
Bathroom          0.0
Car               0.0
Landsize          0.0
BuildingArea      0.0
PropAge           0.0
Propertycount     0.0
Suburb_num        0.0
Method_num        0.0
Regionname_num    0.0
dtype: float64

In [28]:
X = df1.copy()
y = df.Price

## Starting with decision tree menthod and train, test, and validate model

In [30]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(X, y, random_state=10)

from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()


dtr.fit(train_X, train_y)

dtr

DecisionTreeRegressor()

In [31]:
predictions_y = dtr.predict(test_X)

In [32]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(test_y, predictions_y)

In [33]:
mae

256306.3817051219

In [40]:
## Checking decision tree property

print(f'features Importance: {dict(zip(dtr.feature_names_in_, dtr.feature_importances_))}')

features Importance: {'Rooms': np.float64(0.17951679703655496), 'Type_num': np.float64(0.09029745431537044), 'Distance': np.float64(0.21231243268068964), 'Bedroom2': np.float64(0.005263314627475058), 'Bathroom': np.float64(0.04804722601985626), 'Car': np.float64(0.013700667360711823), 'Landsize': np.float64(0.10983263762704987), 'BuildingArea': np.float64(0.07329629106456657), 'PropAge': np.float64(0.03566319151058723), 'Propertycount': np.float64(0.044596633947660724), 'Suburb_num': np.float64(0.030811415432170232), 'Method_num': np.float64(0.0104248678147402), 'Regionname_num': np.float64(0.14623707056256724)}

In [43]:
def test_tree_depth(max_leaf_nodes, train_X, test_X, train_y, test_y):
    dtr = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=10)
    dtr.fit(train_X, train_y)
    predictions = dtr.predict(test_X)
    mae = mean_absolute_error(test_y, predictions)
    print(f'Mean Absolute error for max leaf node {max_leaf_nodes} is : {mae}')
    return mae

In [46]:
b_leaf = {}
for n_leaf in [10,50,100,500,1000]:
    mae = test_tree_depth(max_leaf_nodes=n_leaf, 
                          train_X=train_X, test_X=test_X, train_y=train_y, test_y=test_y)
    b_leaf[n_leaf] = mae
best_max_leaf = min(b_leaf, key = b_leaf.get)

Mean Absolute error for max leaf node 10 is : 330388.45892627945
Mean Absolute error for max leaf node 50 is : 255818.59713240014
Mean Absolute error for max leaf node 100 is : 239848.31559237686
Mean Absolute error for max leaf node 500 is : 225142.67828767136
Mean Absolute error for max leaf node 1000 is : 227480.42230498008

In [51]:
best_dtr = DecisionTreeRegressor(max_leaf_nodes=best_max_leaf, random_state=1)
best_dtr.fit(X, y)

predictions = best_dtr.predict(X)
mae = mean_absolute_error(predictions, y)
mae

158585.3532131155

## Now switching to Random Forest regressor for better accuracy and minimise the error

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor(random_state=10)

rfr.fit(train_X, train_y)

RandomForestRegressor(random_state=10)

In [54]:
predictions = rfr.predict(test_X)
mae = mean_absolute_error(predictions, test_y)
mae

180826.13233276614