In [1]:
from openchart import NSEData
import datetime

# Initialize the NSEData class
nse = NSEData()

In [2]:
nse.historical(symbol='NIFTY', segment='FO', interval='5m')

No data received from the API.

Empty DataFrame
Columns: []
Index: []

In [5]:
# Download master data for NSE and NFO
# nse.download()

# Define the start and end dates (last 30 days)
end_date = datetime.datetime.now()
start_date = end_date - datetime.timedelta(days=740)

In [3]:
symbols = nse.search('NIFTY', 'FO')
symbols

               symbol scripcode            description   type exchange
0            NIFTY 50     26000               NIFTY 50  Index      NSE
1            NIFTY IT     26001               NIFTY IT  Index      NSE
2       NIFTY NEXT 50     26002          NIFTY NEXT 50  Index      NSE
3          NIFTY BANK     26004             NIFTY BANK  Index      NSE
4    NIFTY MIDCAP 100     26005       NIFTY MIDCAP 100  Index      NSE
5           NIFTY 500     26006              NIFTY 500  Index      NSE
6           NIFTY 100     26007              NIFTY 100  Index      NSE
7     NIFTY MIDCAP 50     26008        NIFTY MIDCAP 50  Index      NSE
8        NIFTY REALTY     26009           NIFTY REALTY  Index      NSE
9         NIFTY INFRA     26010   NIFTY INFRASTRUCTURE  Index      NSE
10          INDIA VIX     26011              INDIA VIX  Index      NSE
11       NIFTY ENERGY     26012           NIFTY ENERGY  Index      NSE
12         NIFTY FMCG     26013             NIFTY FMCG  Index      NSE
13          NIFTY MNC     26014              NIFTY MNC  Index      NSE
14       NIFTY PHARMA     26015           NIFTY PHARMA  Index      NSE
15          NIFTY PSE     26016              NIFTY PSE  Index      NSE
16     NIFTY PSU BANK     26017         NIFTY PSU BANK  Index      NSE
17  NIFTY SERV SECTOR     26018  NIFTY SERVICES SECTOR  Index      NSE
18   NIFTY SMLCAP 100     26019     NIFTY SMALLCAP 100  Index      NSE
19          NIFTY 200     26020              NIFTY 200  Index      NSE

In [6]:
# Fetch 5-minute historical data for RELIANCE
data = nse.historical(
    symbol='NIFTY2620324900PE', #NIFTY, BANKNIFTY, FINNIFTY, NIFTY2620324900PE
    start=start_date,
    end=end_date,
    interval='5m',
    segment='FO'
)

# Display the fetched data
if not data.empty:
    print("5-minute historical data for RELIANCE (Last 30 days):")
    print(data)
else:
    print("No data available for RELIANCE for the specified time period.")

No data received from the API.
No data available for RELIANCE for the specified time period.

In [26]:
chg=data["Close"].diff(1)

In [28]:
display(chg)

Timestamp
2026-01-02 10:15:51     NaN
2026-01-05 12:01:55    0.35
2026-01-05 12:17:56   -0.35
2026-01-06 11:14:58    0.85
2026-01-06 11:15:59    1.50
                       ...
2026-01-27 14:49:59   -8.95
2026-01-27 14:54:59   -9.70
2026-01-27 14:59:59   -2.30
2026-01-27 15:04:59   -4.00
2026-01-27 15:09:59   -5.70
Name: Close, Length: 800, dtype: float64

In [1]:
from NSE_Utility import NseUtils

nse = NseUtils()

In [2]:
nse.get_live_option_chain(symbol='BANKNIFTY',expiry_date='24-02-2026' )

{}

KeyError: 'records'